#!/usr/bin/env python3
"""Merge the problem solution LaTeX fragments into one .tex file."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


DEFAULT_INPUT_DIR = Path("Λύσεις προβλημάτων")
DEFAULT_OUTPUT_NAME = "merged_solutions_problems.tex"
SOLUTION_RE = re.compile(r"^solution_problem_(\d+)\.tex$")


def problem_number(path: Path) -> int:
    match = SOLUTION_RE.match(path.name)
    if not match:
        raise ValueError(f"Invalid solution filename: {path.name}")
    return int(match.group(1))


def find_solution_files(input_dir: Path) -> list[Path]:
    files = [
        path
        for path in input_dir.iterdir()
        if path.is_file() and SOLUTION_RE.match(path.name)
    ]
    return sorted(files, key=problem_number)


def warn_for_missing_numbers(files: list[Path]) -> None:
    if not files:
        return

    numbers = [problem_number(path) for path in files]
    expected = set(range(min(numbers), max(numbers) + 1))
    missing = sorted(expected.difference(numbers))
    if missing:
        missing_text = ", ".join(str(number) for number in missing)
        print(f"Warning: missing solution numbers: {missing_text}", file=sys.stderr)


def build_merged_tex(files: list[Path]) -> str:
    parts = [
        "% This file is generated by merge_problem_solutions.py.",
        "% Do not edit it by hand; edit the individual solution_problem_*.tex files.",
        "",
    ]

    for path in files:
        number = problem_number(path)
        body = path.read_text(encoding="utf-8").strip()
        parts.extend(
            [
                f"%=========== ΛΥΣΗ ΠΡΟΒΛΗΜΑΤΟΣ {number:02d} ===========",
                body,
                f"%=========== ΤΕΛΟΣ ΛΥΣΗΣ ΠΡΟΒΛΗΜΑΤΟΣ {number:02d} ===========",
                "",
            ]
        )

    return "\n".join(parts).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Merge LaTeX files named solution_problem_*.tex from a folder "
            "into one combined .tex file."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help=f"Folder with solution files. Default: {DEFAULT_INPUT_DIR}",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(
            "Output .tex file. Default: "
            f"<input-dir>/{DEFAULT_OUTPUT_NAME}"
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_dir = args.input_dir
    output_path = args.output or input_dir / DEFAULT_OUTPUT_NAME

    if not input_dir.is_dir():
        print(f"Error: input directory not found: {input_dir}", file=sys.stderr)
        return 1

    files = find_solution_files(input_dir)
    if not files:
        print(f"Error: no solution_problem_*.tex files found in {input_dir}", file=sys.stderr)
        return 1

    input_paths = {path.resolve() for path in files}
    if output_path.resolve() in input_paths:
        print("Error: output path must not be one of the input solution files.", file=sys.stderr)
        return 1

    warn_for_missing_numbers(files)
    merged_tex = build_merged_tex(files)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(merged_tex, encoding="utf-8")

    print(f"Merged {len(files)} solution files into: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
