# autogenerated by txs
#include:amsmath
#include:etextools
#include:etoolbox
#include:letltxmacro
\csname#S
\csxdefall{arg1}#S
\csxdefaux{arg1}#S
\forlistloop#S
\ifcsedef{arg1}#S
\meaningx{arg1}#S
\newcommandsequence{arg1}#S
\renewcommandsequence{arg1}#S
\skipInPDFTOC{arg1}#S
\string#S
\vanishprotect#S
