# autogenerated by txs
#include:amsmath
#include:amssymb
#include:boxedminipage
#include:ifpdf
#include:latex-document
#include:latex-mathsymbols
#include:mathpazo
#include:tex
\begin{problem}#S
\begin{solution}#S
\end{problem}#S
\end{solution}#S
\headerblock#S
\problemlist{arg1}#S
