# autogenerated by txs
#include:enumitem
#include:ifthen
#include:sectsty
#include:tikz
#include:tkz-euclide
\eggrafo#S
\eggrafo#S
\eggrafo#S
\eggrafo#S
\eggrafo#S
\eidos#S
\eidos#S
\titlos{arg1}{arg2}#S
\xroma{arg1}#S
\xrwma#S
\xrwma#S
