# autogenerated by txs
\BadFileLoadOrder{arg1}{arg2}{arg3}#S
\FBsuboheight#S
\IncompatiblePackages{arg1}{arg2}{arg3}{arg4}#S
\NagDeclareFloat{arg1}#S
\NotASwitch{arg1}#S
\NotAnEnvironment{arg1}#S
\ObsoleteCS{arg1}{arg2}{arg3}#S
\ObsoleteClass{arg1}{arg2}{arg3}#S
\ObsoleteEnv{arg1}{arg2}{arg3}#S
\ObsoletePackage{arg1}{arg2}{arg3}#S
\PackageInfoNoLine{arg1}{arg2}#S
\SuggestedPackage{arg1}{arg2}#S
\csname#S
\nag#S
