# autogenerated by txs
#include:enumitem
#include:ifthen
#include:sectsty
#include:tikz
#include:tkz-euclide
#include:xcolor
\eidos#S
\ekthetesdeiktes#S
\kaliepityxia#S
\kath#S
\kathigiths#S
\keimeno#S
\monades{arg1}#S
\titlos{arg1}{arg2}{arg3}#S
\tmhma#S
\xroma{arg1}#S
\xrwma#S
