# autogenerated by txs
#include:wrapfig
\begin{WrapText1}#S
\begin{WrapText2}#S
\end{WrapText1}#S
\end{WrapText2}#S
\wrapl{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\wrapr{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
