#include:adjustbox
#include:booktabs
#include:calc
#include:enumitem
#include:extarrows
#include:graphicx
#include:hhline
#include:mathtools
#include:multicol
#include:multirow
#include:pgfplots
#include:regexpatch
#include:systeme
#include:tabularx
#include:tikz
#include:tkz-euclide
#include:wrapfig
\swstolathos
\swstolathosd
\swstolathospan
\kaliepityxia
\monades{arithmos}
\titlos
\thewria
\askhseis
\xrwma
\gymnasio
\wrapr{apost_keim}{grammes}{perithorio}{apost_eik}{eikona}{keimeno}
\wrapl{apost_keim}{grammes}{perithorio}{apost_eik}{eikona}{keimeno}
\Orismos{onoma}
\Thewrhma{onoma}
\Methodologia{onoma}
\orismoi
\thewrhmata
\methodoi
\apodeiksi
\lysh
\eng{keimeno}
\Askhsh{kathgoria}
\Paradeigma{kathgoria}
\Lymena
\Alyta
\orag{shmeio}{mhkos}{keimeno}
\kag{shmeio}{mhkos}{keimeno}
\Pag{gwnia}{shmeio}{mhkos}{keimeno}
\hm{gwnia}
\syn{gwnia}
\ef{gwnia}
\syf{gwnia}
\bhm{gwnia}
\bsyn{gwnia}
\bef{gwnia}
\bsyf{gwnia}
\eq{keimeno}
\eqq{panw}{katw}
\xrisimoi
\twocolkentro{keimeno}
\diasthma{akro1_onoma}{akro2_onoma}{akro1}{akro2}{ypsos}{xrwma}
\kyrth
\koilh
\auxousa
\fthinousa
\Xapeiro{akro}{thesi}{mhkos}{ypsos}{xrwma}
\apeiroX{akro}{thesi}{mhkos}{ypsos}{xrwma}
\akro{kleisto_anoixto}{thesi}
\axonas{katw}{anw}
\dianysma{[epiloges]}{arxi}{telos}{on_arxis}{on_telous}
\ellipsh{a}{b}
\parabolh{p}{katw_akro}{panw_akro}
\gwndian{dian_a_onoma}{dian_b_onoma}
\polygon{[epiloges]}{v}{megethos}{onomata_koryfwn}{epiloges}
\triganiswsh{gwnia1}{gwnia2}{shmeio1}{shmeio2}
\trigkyklos
\ekthetesdeiktes
\analyshseprwtous{arithmos}
\analyshseprwtouskatheta{arithmos}
\vresprwtous{plhthos_prwtwn}
\bmath{keimeno_math}
\dpn{onoma_dianysmatos}
\dsx{onoma_dianysmatos}
\horner[platos]{syntelestes}{rho}
\horner*[platos]{syntelestes}{rho}
\MATset\Matrix(onoma) {grammh;grammh;...}
\MATrowreduce{pinakas}
\MATpluq{pinakas}
%----------- ΕΙΔΙΚΕΣ ΣΥΝΑΡΤΗΣΕΙΣ -----------------
\BetaFun{x}{y}
\GammaFun{z}
\ErrorFun{z}
\ErrorCFun{z}
\SiInt{x}
\CiInt{x}
\ZetaFun{s}
\DawsonInt{x}
%--------------------------------------------------