# autogenerated by txs
#include:fancyvrb
#include:graphicx
#include:ifplatform
#include:pgfkeys
#include:verbatimcopy
\ASYPICcomparefiles{arg1}{arg2}#S
\AsyCompileIfNecessary#S
\RequireAsyRecompile#S
\asyheader#S
\asypicture#S
\asyset{arg1}#S
\copyfile{arg1}{arg2}#S
\deletefile{arg1}#S
\expandafter#S
\getfontsize#S
