# autogenerated by txs
#include:ifpdf
#include:ifplatform
#include:pst-pdf
#include:xkeyval
\APPmakepictures#S
\NotIfFileExists{arg1}{arg2}#S
\OnlyIfFileExists{arg1}{arg2}#S
\app#S
\mathfig{arg1}{arg2}#S
\matlabfig{arg1}{arg2}#S
\psfragfig{arg1}{arg2}#S
