# autogenerated by txs
#include:enumitem
#include:fontawesome
#include:ifthen
#include:sectsty
#include:tikz
#include:tkz-euclide
#include:xcolor
\email#S
\kathigiths#S
\mathima#S
\onoma#S
\thl#S
\titlos{arg1}{arg2}{arg3}#S
\xroma{arg1}#S
\xrwma#S
