# autogenerated by txs
#include:\AddCounterPattern*[exsheets]{chapter
#include:\DeclareTranslationFallback{exsheets-exercise-name
#include:\ProvidesExplPackage
#include:\cs_if_exist:NT\thechapter
#include:cntformats}
#include:expl3
#include:tasks
#include:translations}
#include:ulem
#include:xparse}
#include:{
#include:{exsheets
\exp_not#S
