# autogenerated by txs
#include:keyval
\DefaultLhang#S
\DefaultLoversize#S
\DefaultLraise#S
\DefaultOptionsFile#S
\LettrineFont#S
\LettrineFontEPS#S
\LettrineFontHook#S
\LettrineOptionsFor{arg1}{arg2}#S
\LettrineTestString#S
\LettrineTextFont#S
\color#S
\lettrine#S
\textcolor#S
\theDefaultDepth
\theDefaultLines
