# autogenerated by txs
#include:ifluatex
#include:luatexbase-loader
\MessageBreak#S
\RequireLuaModule{arg1}#S
\csname#S
\empty#S
\expandafter#S
\ifluatex#S
\luatexrevision#S
\luatexversion#S
\x#S
\x#S
\x{arg1}#S
\x{arg1}#S
\y{arg1}#S
