# autogenerated by txs
#include:enumitem
#include:fontawesome
#include:ifthen
#include:sectsty
#include:tikz
#include:tkz-euclide
#include:xcolor
\Askhsh{arg1}#S
\Paradeigma{arg1}#S
\begin{Methodos}#S
\eidos#S
\end{Methodos}#S
\lysh#S
\theMethodos
\theparadeigma
\titlos{arg1}{arg2}{arg3}#S
\xrwma#S
